# OpenNEM Emission Flows

Tests and outputs for OpenNEM emission flows.

In [1]:
"""
Notebook for flow emissions
"""

# supress debug + import warnings
%reload_ext autoreload
%autoreload 2
%config IPCompleter.greedy=True

from notebook_init import settings

import pytz
import logging
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from opennem.schema.network import NetworkNEM
from opennem.db import db_connect 
from opennem.utils.http import http

engine_local = db_connect("postgresql://opennem:opennem@127.0.0.1:15433/opennem")
engine_dev = db_connect("postgresql://opennem:qeAZ4AWwmKcEJGp7@opennem03:15433/opennem_dev")
engine = db_connect("postgresql://opennem:qeAZ4AWwmKcEJGp7@opennem03:15433/opennem")

logger = logging.getLogger("console")

def get_database_engine():
    return engine_dev


 * INFO Loading OpenNEM ENV staging
 * INFO OpenNEM Version: 3.9.0-rc.8. Python version: 3.9.10. System: macOS-11.6-arm64-arm-64bit
 * INFO Loading env file: /Users/n/Dropbox/Projects/Opennem/opennem/notebooks/.env


In [42]:

def load_interconnector_intervals(date_start: datetime, date_end: datetime) -> pd.DataFrame:
    """Load interconnectors for a date range"""
    engine = get_database_engine()
    network = NetworkNEM

    query = """
        select
            fs.trading_interval at time zone 'AEST' as trading_interval,
            coalesce(fs.generated, 0) as generated,
            coalesce(fs.eoi_quantity, 0) as energy,
            f.interconnector_region_to,
            f.interconnector_region_from
        from facility_scada fs
        left join facility f on f.code = fs.facility_code
        where
            f.interconnector is True
            and f.network_id IN ('NEM')
            and fs.trading_interval >= '{date_start}T00:00:00+10:00'
            and fs.trading_interval < '{date_end}T00:00:00+10:00'
    """.format(
        date_start=date_start.date(), date_end=date_end.date()
    )

    df_gen = pd.read_sql(query, con=engine, index_col="trading_interval")

    logger.debug(query)
    
    df_gen.trading_interval = df.apply(
        lambda x: pd.Timestamp(x.trading_interval, tz=network.get_fixed_offset()), axis=1
    )

    return df_gen


def load_energy_intervals(date_start: datetime, date_end: datetime) -> pd.DataFrame:
    """Fetch all emissions for all stations"""

    engine = get_database_engine()

    query = """
        select
            fs.trading_interval at time zone 'AEST' as trading_interval,
            f.network_id,
            f.network_region,
            f.fueltech_id,
            fs.facility_code as fs_duid,
            f.code as duid,
            coalesce(fs.generated, 0) as power,
            coalesce(fs.eoi_quantity, 0) as energy,
            coalesce(fs.eoi_quantity * f.emissions_factor_co2, 0) as emissions
        from facility_scada fs
        left join facility f on fs.facility_code = f.code
        where
            fs.trading_interval >= '{date_start}T00:00:00+10:00'
            and fs.trading_interval < '{date_end}T00:00:00+10:00'
            and f.network_id IN ('NEM')
            -- and fs.eoi_quantity is not null
            and f.interconnector is False
        order by 1 asc;
    """.format(
        date_start=date_start.date(), date_end=date_end.date()
    )

    logger.debug(query)

    df_gen = pd.read_sql(query, con=engine)

    return df_gen



In [43]:
day = datetime.fromisoformat("2022-03-07T00:00:00").replace(tzinfo=NetworkNEM.get_fixed_offset(), microsecond=0, hour=0, minute=0, second=0)
day_next = day + timedelta(days=1)

df_gen = load_energy_intervals(date_start=day, date_end=day_next)
df_gen

trading_interval network_id network_region    fueltech_id   fs_duid  \
0      2022-03-07 00:00:00        NEM           NSW1          hydro    TUMUT3   
1      2022-03-07 00:00:00        NEM            SA1       gas_ocgt   DRYCGT1   
2      2022-03-07 00:00:00        NEM            SA1       gas_ocgt   DRYCGT2   
3      2022-03-07 00:00:00        NEM           NSW1       gas_ocgt   URANQ13   
4      2022-03-07 00:00:00        NEM           NSW1       gas_ocgt   URANQ12   
...                    ...        ...            ...            ...       ...   
102522 2022-03-07 23:55:00        NEM           TAS1       gas_ocgt  BBTHREE2   
102523 2022-03-07 23:55:00        NEM           TAS1       gas_ocgt  BBTHREE3   
102524 2022-03-07 23:55:00        NEM           VIC1       gas_ocgt     BDL01   
102525 2022-03-07 23:55:00        NEM           VIC1       gas_ocgt     BDL02   
102526 2022-03-07 23:55:00        NEM           NSW1  solar_utility  BERYLSF1   

            duid  power  energy  emissions  
0         TUMUT3    0.0     0.0        0.0  
1        DRYCGT1    0.0     0.0        0.0  
2        DRYCGT2    0.0     0.0        0.0  
3        URANQ13    0.0     0.0        0.0  
4        URANQ12    0.0     0.0        0.0  
...          ...    ...     ...        ...  
102522  BBTHREE2    0.0     0.0        0.0  
102523  BBTHREE3    0.0     0.0        0.0  
102524     BDL01    0.0     0.0        0.0  
102525     BDL02    0.0     0.0        0.0  
102526  BERYLSF1    0.0     0.0        0.0  

[102527 rows x 9 columns]

In [7]:
df_ic = load_interconnector_intervals(date_start=day, date_end=day_next)
df_ic

generated      energy interconnector_region_to  \
trading_interval                                                      
2022-03-07 23:55:00  185.73688  104.111159                      SA1   
2022-03-07 23:50:00  215.07448    0.000000                      SA1   
2022-03-07 23:45:00  232.80214    0.000000                      SA1   
2022-03-07 23:40:00  252.57758    0.000000                      SA1   
2022-03-07 23:35:00  202.25457    0.000000                      SA1   
...                        ...         ...                      ...   
2022-03-07 00:20:00 -357.66049    0.000000                     VIC1   
2022-03-07 00:15:00 -361.60214    0.000000                     VIC1   
2022-03-07 00:10:00 -339.90189    0.000000                     VIC1   
2022-03-07 00:05:00 -411.98628    0.000000                     VIC1   
2022-03-07 00:00:00 -413.21895    0.000000                     VIC1   

                    interconnector_region_from  
trading_interval                                
2022-03-07 23:55:00                       VIC1  
2022-03-07 23:50:00                       VIC1  
2022-03-07 23:45:00                       VIC1  
2022-03-07 23:40:00                       VIC1  
2022-03-07 23:35:00                       VIC1  
...                                        ...  
2022-03-07 00:20:00                       TAS1  
2022-03-07 00:15:00                       TAS1  
2022-03-07 00:10:00                       TAS1  
2022-03-07 00:05:00                       TAS1  
2022-03-07 00:00:00                       TAS1  

[1728 rows x 4 columns]

In [6]:
dict(zip(["s", "q", "t", "n", "v", "v-n", "n-q", "n-v", "v-s", "v-t"], range(10)))

{'s': 0,
 'q': 1,
 't': 2,
 'n': 3,
 'v': 4,
 'v-n': 5,
 'n-q': 6,
 'n-v': 7,
 'v-s': 8,
 'v-t': 9}

In [8]:
# calc_emissions
df_gen_em = df_gen.groupby(["trading_interval", "network_region", "fueltech_id"])[
        ["energy", "emissions"]
    ].sum()
df_gen_em.reset_index(inplace=True)

In [10]:
df_gen_em.iloc[210:300]

trading_interval network_region          fueltech_id      energy  \
210 2022-03-07 00:25:00           NSW1                pumps    0.000000   
211 2022-03-07 00:25:00           NSW1        solar_utility    0.000000   
212 2022-03-07 00:25:00           NSW1                 wind  499.410302   
213 2022-03-07 00:25:00           QLD1     battery_charging    0.000000   
214 2022-03-07 00:25:00           QLD1  battery_discharging    0.000000   
..                  ...            ...                  ...         ...   
295 2022-03-07 00:35:00           QLD1     battery_charging    0.000000   
296 2022-03-07 00:35:00           QLD1  battery_discharging    0.000000   
297 2022-03-07 00:35:00           QLD1    bioenergy_biomass    0.000000   
298 2022-03-07 00:35:00           QLD1           coal_black    0.000000   
299 2022-03-07 00:35:00           QLD1           distillate    0.000000   

     emissions  
210        0.0  
211        0.0  
212        0.0  
213        0.0  
214        0.0  
..         ...  
295        0.0  
296        0.0  
297        0.0  
298        0.0  
299        0.0  

[90 rows x 5 columns]

In [22]:
interconnector_di = df_ic

dx = (
    interconnector_di.groupby(["interconnector_region_from", "interconnector_region_to"])
    .energy.sum()
    .reset_index()
)
dy = dx.rename(
    columns={
        "interconnector_region_from": "interconnector_region_to",
        "interconnector_region_to": "interconnector_region_from",
    }
)

# set indexes
dy.set_index(["interconnector_region_to", "interconnector_region_from"], inplace=True)
dx.set_index(["interconnector_region_to", "interconnector_region_from"], inplace=True)

dy["energy"] *= -1

# 
dx.loc[dx.energy < 0, "energy"] = 0
dy.loc[dy.energy < 0, "energy"] = 0

{
    **dx.to_dict()["energy"],    
    **dy.to_dict()["energy"],
}

{('QLD1', 'NSW1'): 0.0,
 ('VIC1', 'TAS1'): 0.0,
 ('NSW1', 'VIC1'): 2928.0835116666667,
 ('SA1', 'VIC1'): 2263.1900225,
 ('NSW1', 'QLD1'): 1845.3780125,
 ('TAS1', 'VIC1'): 9345.725368333333,
 ('VIC1', 'NSW1'): 0.0,
 ('VIC1', 'SA1'): 0.0}

In [33]:

def interconnector_dict(interconnector_di: pd.DataFrame) -> pd.DataFrame:
    dx = (
        interconnector_di.groupby(["interconnector_region_from", "interconnector_region_to"])
        .energy.sum()
        .reset_index()
    )
    dy = dx.rename(
        columns={
            "interconnector_region_from": "interconnector_region_to",
            "interconnector_region_to": "interconnector_region_from",
        }
    )

    # set indexes
    dy.set_index(["interconnector_region_to", "interconnector_region_from"], inplace=True)
    dx.set_index(["interconnector_region_to", "interconnector_region_from"], inplace=True)

    # dy["energy"] *= -1

    # 
    dx.loc[dx.energy < 0, "energy"] = dx["energy"] * -1
    dy.loc[dy.energy < 0, "energy"] = dy["energy"] * -1
    
    dx["energy"] *= 1000
    dy["energy"] *= 1000

    return {
        **dx.to_dict()["energy"],    
        **dy.to_dict()["energy"],
    }


interconnector_dict(df_ic)

{('QLD1', 'NSW1'): 1845378.0125,
 ('VIC1', 'TAS1'): 9345725.368333332,
 ('NSW1', 'VIC1'): 2928083.5116666667,
 ('SA1', 'VIC1'): 2263190.0225,
 ('NSW1', 'QLD1'): 1845378.0125,
 ('TAS1', 'VIC1'): 9345725.368333332,
 ('VIC1', 'NSW1'): 2928083.5116666667,
 ('VIC1', 'SA1'): 2263190.0225}

In [34]:

def region_flows(interconnector_di: pd.DataFrame, day: datetime) -> pd.DataFrame:
    dx = (
        interconnector_di.groupby(["interconnector_region_from", "interconnector_region_to"])
        .generated.sum()
        .reset_index()
    )
    dy = dx.rename(
        columns={
            "interconnector_region_from": "interconnector_region_to",
            "interconnector_region_to": "interconnector_region_from",
        }
    )

    # set indexes
    dy.set_index(["interconnector_region_to", "interconnector_region_from"], inplace=True)
    dx.set_index(["interconnector_region_to", "interconnector_region_from"], inplace=True)

    dy["generated"] *= -1

    #
    dx.loc[dx.generated < 0, "generated"] = 0
    dy.loc[dy.generated < 0, "generated"] = 0


    # interconnector_dict(df_ic)
    f = pd.concat([dx, dy])

    energy_flows = pd.DataFrame({
        "energy_imports": f.groupby("interconnector_region_to").generated.sum(),
        "energy_exports": f.groupby("interconnector_region_from").generated.sum()
    }
    )
    
    
    energy_flows["network_id"] = "NEM"
    energy_flows["trading_interval"] = day
    
    energy_flows.reset_index(inplace=True)
    energy_flows.rename(columns={"index": "network_region"}, inplace=True)
    energy_flows.set_index(["trading_interval", "network_id", "network_region"], inplace=True)
    
    return energy_flows

region_flows(df_ic, day=day)

energy_imports  \
trading_interval          network_id network_region                   
2022-03-07 00:00:00+10:00 NEM        NSW1               57554.07467   
                                     QLD1                   0.00000   
                                     SA1                27430.59075   
                                     TAS1              112109.41651   
                                     VIC1                   0.00000   

                                                     energy_exports  
trading_interval          network_id network_region                  
2022-03-07 00:00:00+10:00 NEM        NSW1                   0.00000  
                                     QLD1               22119.77681  
                                     SA1                    0.00000  
                                     TAS1                   0.00000  
                                     VIC1              174974.30512

In [35]:
from typing import Dict

def power(df_emissions: pd.DataFrame, df_ic: pd.DataFrame) -> Dict:
    """ """
    df_emissions = df_emissions.reset_index()
    power_dict = dict(df_emissions.groupby(df_emissions.network_region).energy.sum())
    power_dict.update(interconnector_dict(df_ic))
    return power_dict

power_dict = power(df_gen_em, df_ic)
power_dict

{'NSW1': 99876.21579870833,
 'QLD1': 92799.05102995834,
 'SA1': 14571.279994583334,
 'TAS1': 9635.90418625,
 'VIC1': 68247.643680625,
 ('QLD1', 'NSW1'): 1845378.0125,
 ('VIC1', 'TAS1'): 9345725.368333332,
 ('NSW1', 'VIC1'): 2928083.5116666667,
 ('SA1', 'VIC1'): 2263190.0225,
 ('NSW1', 'QLD1'): 1845378.0125,
 ('TAS1', 'VIC1'): 9345725.368333332,
 ('VIC1', 'NSW1'): 2928083.5116666667,
 ('VIC1', 'SA1'): 2263190.0225}

In [36]:
from typing import Dict

def simple_exports(
    emissions_di: pd.DataFrame, power_dict: Dict, from_regionid: str, to_regionid: str
):
    dx = emissions_di[emissions_di.network_region == from_regionid]

    try:
        ic_flow = power_dict[from_regionid, to_regionid]
    except KeyError:
        return 0

    emissions_sum = dx.energy.sum() * dx.emissions.sum()
    export_value = 0

    if emissions_sum and emissions_sum > 0:
        export_value = ic_flow / emissions_sum

    return export_value


def emissions(df_emissions: pd.DataFrame, power_dict: Dict) -> Dict:
    df_emissions = df_emissions.reset_index()
    emissions_dict = dict(df_emissions.groupby(df_emissions.network_region).emissions.sum())

    # simple_flows = [[2, 1], [3, 5], [4, 5]]
    simple_flows = [["QLD1", "NSW1"], ["SA1", "VIC1"], ["TAS1", "VIC1"]]

    for from_regionid, to_regionid in simple_flows:
        try:
            emissions_dict[(from_regionid, to_regionid)] = simple_exports(
                df_emissions, power_dict, from_regionid, to_regionid
            )
        except Exception as e:
            logger.error(e)

    return emissions_dict

emissions_dict = emissions(df_gen_em, power_dict)
emissions_dict

{'NSW1': 63576.32150005468,
 'QLD1': 72424.89831325083,
 'SA1': 1207.01427219245,
 'TAS1': -0.18832717299999996,
 'VIC1': 55621.219853363276,
 ('QLD1', 'NSW1'): 0.0002745705239764611,
 ('SA1', 'VIC1'): 0.12867995814508557,
 ('TAS1', 'VIC1'): 0}

In [37]:
# 1 - "NSW1"
# 2 - "QLD1"
# 3 - "SA1"
# 4 - "TAS1"
# 5 - "VIC1"

def demand(power_dict: Dict) -> Dict:
    d = {}
    
    if "NSW1" not in power_dict:
        raise Exception("Missing generation info")
        
    d["NSW1"] = (
        power_dict["NSW1"]
        + power_dict[("QLD1", "NSW1")]
        + power_dict[("VIC1", "NSW1")]
        - power_dict[("NSW1", "VIC1")]
        - power_dict[("NSW1", "QLD1")]
    )
    d["QLD1"] = power_dict["QLD1"] + power_dict[("NSW1", "QLD1")] - power_dict[("QLD1", "NSW1")]
    d["SA1"] = power_dict["SA1"] + power_dict[("VIC1", "SA1")] - power_dict[("SA1", "VIC1")]
    d["TAS1"] = power_dict["TAS1"] + power_dict[("VIC1", "TAS1")] - power_dict[("TAS1", "VIC1")]
    d["VIC1"] = (
        power_dict["VIC1"]
        + power_dict[("NSW1", "VIC1")]
        + power_dict[("SA1", "VIC1")]
        + power_dict[("TAS1", "VIC1")]
        - power_dict[("VIC1", "NSW1")]
        - power_dict[("VIC1", "TAS1")]
        - power_dict[("VIC1", "SA1")]
    )
    return d

demand_dict = demand(power_dict)
demand_dict

{'NSW1': 99876.21579870884,
 'QLD1': 92799.0510299583,
 'SA1': 14571.279994583223,
 'TAS1': 9635.904186250642,
 'VIC1': 68247.6436806256}

In [38]:

def fill_row(a, row, pairs, _var_dict) -> None:
    for _var, value in pairs:
        a[row][_var_dict[_var]] = value


def fill_constant(a, _var, value, _var_dict) -> None:
    idx = _var_dict[_var]
    a[idx] = value


def solve_flows(emissions_di, interconnector_di) -> pd.DataFrame:
    #
    power_dict = power(emissions_di, interconnector_di)
    emissions_dict = emissions(emissions_di, power_dict)
    
    try:
        demand_dict = demand(power_dict)
    except Exception as e:
        print("Error: {}".format(e))
        return None

    a = np.zeros((10, 10))
    _var_dict = dict(zip(["s", "q", "t", "n", "v", "v-n", "n-q", "n-v", "v-s", "v-t"], range(10)))

    # emissions balance equations
    fill_row(a, 0, [["s", 1], ["v-s", -1]], _var_dict)
    fill_row(a, 1, [["q", 1], ["n-q", -1]], _var_dict)
    fill_row(a, 2, [["t", 1], ["v-t", -1]], _var_dict)
    fill_row(a, 3, [["n", 1], ["v-n", -1], ["n-q", 1], ["n-v", 1]], _var_dict)
    fill_row(a, 4, [["v", 1], ["v-n", 1], ["n-v", -1], ["v-s", 1], ["v-t", 1]], _var_dict)

    # emissions intensity equations
    fill_row(a, 5, [["n-q", 1], ["n", -power_dict[("NSW1", "QLD1")] / demand_dict["NSW1"]]], _var_dict)
    fill_row(a, 6, [["n-v", 1], ["n", -power_dict[("NSW1", "VIC1")] / demand_dict["NSW1"]]], _var_dict)
    fill_row(a, 7, [["v-t", 1], ["v", -power_dict[("VIC1", "TAS1")] / demand_dict["VIC1"]]], _var_dict)
    fill_row(a, 8, [["v-s", 1], ["v", -power_dict[("VIC1", "SA1")] / demand_dict["VIC1"]]], _var_dict)
    fill_row(a, 9, [["v-n", 1], ["v", -power_dict[("VIC1", "NSW1")] / demand_dict["VIC1"]]], _var_dict)

    # constants
    b = np.zeros((10, 1))
    fill_constant(b, "s", emissions_dict["SA1"] - emissions_dict[("SA1", "VIC1")], _var_dict)
    fill_constant(b, "q", emissions_dict["QLD1"] - emissions_dict[("QLD1", "NSW1")], _var_dict)
    fill_constant(b, "t", emissions_dict["TAS1"] - emissions_dict[("TAS1", "VIC1")], _var_dict)
    fill_constant(b, "n", emissions_dict["NSW1"] + emissions_dict[("QLD1", "NSW1")], _var_dict)
    fill_constant(
        b, "v", emissions_dict["VIC1"] + emissions_dict[("SA1", "VIC1")] + emissions_dict[("TAS1", "VIC1")], _var_dict
    )

    # cast nan to 0
    b[np.isnan(b)] = 0
    
    # get result
    result = None

    try:
        result = np.linalg.solve(a, b)
    except Exception as e:
        print("Error: for {}".format(e))
        print(a)
        print(b)
        result = None

    # transform into emission flows
    emission_flows = {}
    
    if result is not None:
        emission_flows["NSW1", "QLD1"] = result[6][0]
        emission_flows["VIC1", "NSW1"] = result[5][0]
        emission_flows["NSW1", "VIC1"] = result[7][0]
        emission_flows["VIC1", "SA1"] = result[8][0]
        emission_flows["VIC1", "TAS1"] = result[9][0]
        
    emission_flows["QLD1", "NSW1"] = emissions_dict["QLD1", "NSW1"]
    emission_flows["TAS1", "VIC1"] = emissions_dict["TAS1", "VIC1"]
    emission_flows["SA1", "VIC1"] = emissions_dict["SA1", "VIC1"]

    # shape into dataframe
    df = pd.DataFrame.from_dict(emission_flows, orient="index")
    df.columns = ["EMISSIONS"]
    df.reset_index(inplace=True)

    return df

sf = solve_flows(df_gen_em, df_ic)
sf

index     EMISSIONS
0  (NSW1, QLD1)  32172.250212
1  (VIC1, NSW1)  21385.263373
2  (NSW1, VIC1)  51048.096781
3   (VIC1, SA1)  16529.212539
4  (VIC1, TAS1)  68256.522610
5  (QLD1, NSW1)      0.000275
6  (TAS1, VIC1)      0.000000
7   (SA1, VIC1)      0.128680

In [41]:



def calc_emissions(df_emissions: pd.DataFrame) -> pd.DataFrame:
    df_gen_em = df_emissions.groupby(["trading_interval", "network_region", "fueltech_id"])[
        ["energy", "emissions"]
    ].sum()
    df_gen_em.reset_index(inplace=True)

    return df_gen_em


def calculate_emission_flows(df_gen: pd.DataFrame, df_ic: pd.DataFrame) -> Dict:

    dx_emissions = calc_emissions(df_gen)
    dx_ic = df_ic

    results = {}
    dt = df_gen.trading_interval.iloc[0]
    while dt <= df_gen.trading_interval.iloc[-1]:
        emissions_di = dx_emissions[dx_emissions.trading_interval == dt]
        interconnector_di = dx_ic[dx_ic.index == dt]

        results[dt] = solve_flows(emissions_di, interconnector_di)
        dt += timedelta(minutes=5)

    return results


def calc_day(day: datetime) -> pd.DataFrame:

    day_next = day + timedelta(days=1)

    df_gen = load_energy_intervals(date_start=day, date_end=day_next)

    df_ic = load_interconnector_intervals(date_start=day, date_end=day_next)

    results_dict = calculate_emission_flows(df_gen, df_ic)

    flow_series = pd.concat(results_dict).reset_index()

    flow_series.rename(
        columns={"level_0": "trading_interval", "index": "network_region"}, inplace=True
    )
    flow_series["region_from"] = flow_series.apply(lambda x: x.network_region[0], axis=1)
    flow_series["region_to"] = flow_series.apply(lambda x: x.network_region[1], axis=1)

    # build the final data frame with both imports and exports
    flow_series_clean = pd.DataFrame(
        {
            "emissions_exports": flow_series.groupby("region_from").EMISSIONS.sum(),
            "emissions_imports": flow_series.groupby("region_to").EMISSIONS.sum(),
            "network_id": "NEM",
            "trading_interval": day,
        }
    )
    
    flow_series_clean.reset_index(inplace=True)
    flow_series_clean.rename(columns={"index": "network_region"}, inplace=True)
    
    flow_series_clean.set_index(["trading_interval", "network_id", "network_region"], inplace=True)
    energy_flows = region_flows(df_ic, day=day)
    
    total_series = flow_series_clean.merge(c, left_index=True, right_index=True)

    return total_series


c = calc_day(day)

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]

 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. nan  1.  0.  0.  0.  0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Error: for Singular matrix
[[ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0. -1.  1.  1.]
 [ 0.  0.  0. nan  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. nan  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. nan  0.  0.  0.  0.  1.]
 [ 0.

NameError: name 'c' is not defined

In [40]:
c

NameError: name 'c' is not defined

In [110]:
b.merge(c, left_index=True, right_index=True)

emissions_exports  \
trading_interval          network_id network_region                      
2022-02-01 00:00:00+10:00 NEM        NSW1                  7609.593793   
                                     QLD1                     0.001871   
                                     SA1                      0.053822   
                                     TAS1                     0.896193   
                                     VIC1                  5062.394161   

                                                     emissions_imports  \
trading_interval          network_id network_region                      
2022-02-01 00:00:00+10:00 NEM        NSW1                  1960.408170   
                                     QLD1                     0.000000   
                                     SA1                   2469.223836   
                                     TAS1                   632.764025   
                                     VIC1                  7610.543808   

                                                     energy_imports  \
trading_interval          network_id network_region                   
2022-02-01 00:00:00+10:00 NEM        NSW1               50818.33551   
                                     QLD1              102207.86914   
                                     SA1                    0.00000   
                                     TAS1               62059.42757   
                                     VIC1                1622.19686   

                                                     energy_exports  
trading_interval          network_id network_region                  
2022-02-01 00:00:00+10:00 NEM        NSW1              102207.86914  
                                     QLD1                   0.00000  
                                     SA1                 1622.19686  
                                     TAS1                   0.00000  
                                     VIC1              112877.76308

In [71]:
b.to_sql("at_network_flows", con=engine_dev, if_exists="append")

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "at_network_flows_pkey"
DETAIL:  Key (trading_interval, network_id)=(2022-01-31 14:00:00+00, NEM) already exists.

[SQL: INSERT INTO at_network_flows (network_region, emissions_exports, emissions_imports, network_id, trading_interval) VALUES (%(network_region)s, %(emissions_exports)s, %(emissions_imports)s, %(network_id)s, %(trading_interval)s)]
[parameters: ({'network_region': 'NSW1', 'emissions_exports': 14756.306115576323, 'emissions_imports': 7989.708275358418, 'network_id': 'NEM', 'trading_interval': datetime.datetime(2022, 2, 1, 0, 0, tzinfo=pytz.FixedOffset(600))}, {'network_region': 'QLD1', 'emissions_exports': 0.0, 'emissions_imports': 12633.568774522046, 'network_id': 'NEM', 'trading_interval': datetime.datetime(2022, 2, 1, 0, 0, tzinfo=pytz.FixedOffset(600))}, {'network_region': 'SA1', 'emissions_exports': 234.2871812934538, 'emissions_imports': 3450.5417042625904, 'network_id': 'NEM', 'trading_interval': datetime.datetime(2022, 2, 1, 0, 0, tzinfo=pytz.FixedOffset(600))}, {'network_region': 'TAS1', 'emissions_exports': 15.967699709495077, 'emissions_imports': 7656.77493036855, 'network_id': 'NEM', 'trading_interval': datetime.datetime(2022, 2, 1, 0, 0, tzinfo=pytz.FixedOffset(600))}, {'network_region': 'VIC1', 'emissions_exports': 19097.02490998956, 'emissions_imports': 2372.9922220572266, 'network_id': 'NEM', 'trading_interval': datetime.datetime(2022, 2, 1, 0, 0, tzinfo=pytz.FixedOffset(600))})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)